### PR TITLE
Metadata review

### LINKED ISSUE #26: Review: Metadata
- [x] David Widger actually has an NACOAF id; `create draft` will now add it automatically if it sees him in the list of transcribers, but I'm sure that change has been since you started. I don't remember what it is, but you can just search for his name on the id.loc.gov site.
- [x] Would you mind putting comments on the transcriptions so we know which is what? With this many, it would be helpful to know so someone doesn't have to open each one to find the one they're looking for. `<!-- Republic -->`, e.g.
- [x] Ditto for the IA scans; can you indicate which dialogues are in each volume? E.g. something like `<!-- Charmides, Lysis, Laches, Protagoras, Euthydemus, Cratylus, Phaedrus, Ion, Symposium -->` for vol. 1. (If there are standard abbreviations for those, those could be used as well.) We want people who are reporting typos to check the scans first, and this will let them know which volume to look in.
- [x] Although it's never been codified in SEMoS, our de facto standard to date has been to only put the first volume of scans in `imprint`; having them all in `colophon` is fine.
- [x] You list both the PG transcriptions and the OLL ones; was there a reason you needed both? If so, can you put a blurb in the production notes about why?

### PR DESCRIPTION
**Pull request by irontigran**
Address issues raised #26

### CODE REVIEW

**Comment by vr8hub** [comment]
Oops, sorry, I wasn't clear about where the comments go. I don't believe HTML comments can go inside an existing element. They should go above the element like this. A regex search-and-replace should hopefully fix it.
````
<!-- Apology -->
<dc:source>https://www.gutenberg.org/ebooks/1656</dc:source>
````

**Comment by vr8hub** [comment]
Also, I just discovered Cratylus is missing from the vol. 1 list. :)

**Comment by irontigran** [comment]
HTML comments can go inside existing elements - and the epub builds just fine with it. I can still move the comments of course if we want that as a matter of style.

**Comment by vr8hub** [comment]
Ahh, good to know. This is one of those grey areas: it's not covered explicitly in SEMoS, we have other examples, which are formatted as I showed, but I suspect it's more because that's the way the others looked and the style was copied each time. I'll add it to Alex's list; if he doesn't care, then the rest of us don't, either. :)

**Comment by vr8hub** [comment]
Per Alex's response, let's put the comments on a separate line before the source being commented on. That should be a pretty simple regex search-and-replace. (As you might have seen on the list, we've actually had a change in how imprint/colophon are going to be handled, and we're looking to use these comments in the future, so standardizing them is now a thing. :)

**Pull request merged**
